#!/bin/bash
# Kommentar
# ausführen mit ./filename

# Demonstriert getopt zum Auslesen der Optionen -a -b -c -D
# mit eigener Fehlerbehandlung
while getopts abc:D: opt 2>/dev/null
do
   case $opt in
       a) echo "Option a";;
       b) echo "Option b";;
       c) echo "Option c : ($OPTARG)";;
       D) echo "Option D : ($OPTARG)";;
       ?) echo "($0): Ein Fehler bei der Optionsangabe"
   esac
done


echo "Hallo Welt"

