#!/bin/bash
# Skript: skripttemplate
# Use: basis for own scripts. Contains already some standard elements.
#   usage function,
#   options parsing,
#   predefined variables, ...

# Global variables______________________________________________________
SCRIPTNAME=$(basename $0 .sh)
EXIT_SUCCESS=0
EXIT_FAILURE=1
EXIT_ERROR=2
EXIT_BUG=10

# Variables for Options (set devault-values here)_______________________
VERBOSE=n
OPTFILE=""

# Functions_____________________________________________________________
function usage {
  echo "Usage: $SCRIPTNAME [-h] [-v] [-o arg] file ..." >&2
  [[ $# -eq 1 ]] && exit $1 || exit $EXIT_FAILURE
}


# Readout options_______________________________________________________
# The option -h for help should always be available,
# the options -v and -o are exemples. -o has and additional argument,
# be aware of the ":" after the "o"!
while getopts ':o:vh' OPTION ; do
  case $OPTION in
  v) VERBOSE=y
  ;;
  o) OPTFILE="$OPTARG"
  ;;
  h) usage $EXIT_SUCCESS
  ;;
  \?) echo "unknown option \"-$OPTARG\"." >&2
  usage $EXIT_ERROR
  ;;
  :) echo "Option \"-$OPTARG\" needs an argument!" >&2
  usage $EXIT_ERROR
  ;;
  *) echo "This should not have happened - in fact it's impossible!" >&2
  usage $EXIT_BUG
  ;;
  esac
done

# jump above used arguments
shift $(( OPTIND - 1 ))

